# build version
version: '{build}'

# environment settings
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk9

# build and install artifacts
build_script:
  - gradlew.bat --no-daemon assemble

test_script:
  - gradlew.bat --no-daemon check

artifacts:
  - path: 'app/build/libs/scenebuilder-*.jar'
    name: JAR
